name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cópiando dados da master
      uses: actions/checkout@v2

    - name: Configurando python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Instalando Poetry
      run: python -m pip install poetry

    - name: Instalando Sphinx
      run: sudo apt install python3-sphinx -y

    - name: Update version pyproject
      run: |
        pip install requests
        python update_version.py

    - name: Instalando dependencias
      run: |
        poetry install

    - name: Instalando o lint
      run: |
        pip install pylint
        pylint src
      continue-on-error: true

    - name: Realizando testes
      run: poetry run pytest --cov 

    - name: Build package
      run: poetry build -v

    - name: Publicação no PyPI
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
        poetry publish --username __token__ -v